### ISSUE TITLE
Warriors move/fly like concrete fridges

### ISSUE THREAD

**Issue by Vetpetmon** [Vetpetmon-Labs/Wyrms-of-Nyrus#13]
I used the Prober MoveHelper as a base for the Warrior's MoveHelper, so of course there's gonna be a few bugs for the Warrior.

This issue is being made to track and observe any oddities in the AI.

**Comment by Carvercarver1** [comment]
FlyingMobAI.java EntityWyrmWarrior.java are my main suspects.

First things I'd do is check the min and max distances and requisites for the charge attack. They do however more or less manage to follow and attack air targets. So issue is more with the ground based hostiles... but air still needs to be adjusted for precision. But my main suspect here is movehelper. Since all moves are performed, but performed poorly. 

Since  they do follow and fly close to attack but don't fly up it seems, and also can't get closer to their target either staying below a block or above them without touching. They will do damage if you run into them though.
So they... kinda get close and expect to attack but don't. Since they stay away from bounding box just far enough so their attacks cannot reach the target, maybe? Might as well be reason why they cannot fly up.
And since the AI is from prober it is likely that due to their small size they actually can get close and damage
But because of it's thickness it cannot touch the player and pathfinder considers it fine...

So some tuning for values is needed.

It also cannot fly upwards when on ground, so there is a good chance that if player travels over the hill or up something warrior will get stuck.

Addition: they need to periodically strafe in the air to avoid being hit. Or teleport with 50% chance to 1-2 blocks nearby to simulate dodge.

**Comment by Vetpetmon** [comment]
warriors too dummy thick for AI to work properly

**Comment by Vetpetmon** [comment]
Tried to adjust the MoveHelper's motionX/Y/Z to the EXACT size of the hitbox.

So far so good, sometimes the AI still gets stuck.

One small issue: They shoot up into the air past the build limit sometimes.

**Comment by Carvercarver1** [comment]
Needs to have additional goal of getting unstuck if it stays in one spot for too long while it tries to reach stuff. 

Also you need to code-in a height limit they can not go past of. Like distance of air blocks beneath or would height.

**Comment by Vetpetmon** [comment]
Working on height limits as we speak but some interesting things are happening.

1. They don't respect these limits and will still overshoot into the air or down into the void.

Warriors are the ones having the issues here, Probers are doing their best to stay below `y=256`. This even means that they'll avoid going to `y=257` unless if directly under a target's hitbox.

These limits will be defined per-wyrm in configs because Cubic Chunks exists, terrifyingly enough.

(Working on AI is like playing 4D chess. The more you play with it, the more you hate it.)

**Comment by Vetpetmon** [comment]
Been worked on and fixed, Warriors move properly now.
